var AREAS=['Operaciones / tienda','Inventario','Logística / transporte','Servicio al cliente','Finanzas','E-commerce / catálogo','TI / sistemas','Comercial / compras','Proveedor o seller'];
MODS.push({id:'6',title:'6. Gestión operativa e-commerce',short:'Incidencias, excepciones, escalamiento, mesa de control y casos',blurb:'Ya conoces los conceptos: aquí operas. Clasifica, prioriza, escala y resuelve con casos y un simulador de 20 incidencias.',ch:[
{id:'6.1',title:'El ciclo de una incidencia, de punta a punta',min:20,
goal:'Recorrer las etapas de una incidencia (detectar, clasificar, priorizar, asignar, resolver, comunicar, cerrar y analizar) y aplicarlas a un caso.',
body:`<p>Una incidencia (capítulo 2.4) no termina cuando alguien la «arregla». Una gestión ordenada recorre estas etapas:</p>
${T(['Etapa','Qué haces','Qué registras'],[
['1 Detectar','Alguien o algo la nota: picker, cliente, alerta, reporte','Cómo y cuándo se detectó'],
['2 Registrar','La anotas una sola vez, completa','Pedido, SKU, tienda, hora, descripción'],
['3 Clasificar','Le asignas un tipo (stock, picking, logística, cliente, sistema, pago, catálogo…)','Tipo'],
['4 Severidad y prioridad','Decides cuánto daño hace y qué atender primero','Severidad, prioridad'],
['5 Asignar','Responsable y plazo (SLA de resolución)','Responsable, fecha límite'],
['6 Investigar','Buscas la causa, no solo el síntoma','Evidencia y hallazgos'],
['7 Resolver','Corriges el caso concreto','Acción tomada'],
['8 Comunicar','Avisas a quien corresponda, incluido el cliente','Mensaje y hora'],
['9 Cerrar','Con causa raíz y sin pendientes','Causa raíz, fecha de cierre'],
['10 Analizar recurrencia','¿Se repite en el mismo SKU, tienda o turno?','Etiquetas para reportes']])}
<p><b>Severidad</b> es cuánto daño causa (a clientes, ventas, cumplimiento). <b>Prioridad</b> es el orden en que la atiendes: combina severidad con urgencia (cuánto tiempo queda). Una incidencia de severidad media puede ser la primera si su plazo vence en una hora.</p>
<p>El <b>SLA de resolución</b> es el tiempo objetivo para resolver según la severidad. Los tiempos los define cada empresa; los del ejercicio son inventados ${V('SLA de resolución de tu empresa')}. Lo que separa a un buen operador de uno regular casi siempre es el paso 9: cerrar con causa raíz, porque de ahí sale el análisis del capítulo 6.2 y de tu reporte semanal.</p>`,
example:`<p>En «Retail Andino» (ficticio), la incidencia «producto no encontrado» del pedido PED-10231 se registra con SKU, tienda y stock del sistema. Si se cierra con la causa «stock desalineado por recepción sin ingresar», tres semanas después alguien puede ver que ese SKU acumula seis casos y corregir la raíz.</p>`,
ex:{type:'scenario',intro:'Caso guiado. Decide en cada paso y lee el razonamiento.',cases:[{t:'Producto no encontrado en picking',sit:'<p>Son las 14:10. En la tienda Surco, el pedido <b>PED-10231</b> (1 televisor, campaña Cyber) no se encuentra en su ubicación. El sistema muestra 2 unidades. El SLA del pedido vence en 1 hora.</p>',steps:[
{q:'¿Cuál es tu primera acción?',o:[{t:'Cancelar el pedido de inmediato para no incumplir el SLA',p:0,f:'Cancelar es el último recurso: todavía no sabes si el producto existe.'},{t:'Registrar la incidencia con pedido, SKU, tienda y stock del sistema, y avisar al responsable de tienda',p:2,f:'Registrar primero deja evidencia y permite que otros ayuden.'},{t:'Avisar al cliente que su pedido se retrasa',p:1,f:'Puede ser necesario más tarde, pero sin registro ni datos aún no sabes qué decirle.'}]},
{q:'¿Cómo la clasificas?',o:[{t:'Stock (sistema y físico no coinciden)',p:2,f:'El picking es donde se detecta, pero la causa probable es de stock.'},{t:'Logística',p:0,f:'Todavía no hay problema de transporte.'},{t:'Picking, porque el picker no lo encontró',p:1,f:'Válido como síntoma, pero clasificar por causa probable ayuda más al análisis.'}]},
{q:'¿Qué severidad y prioridad le das?',o:[{t:'Alta: el SLA vence en una hora y es un pedido de campaña',p:2,f:'Combina daño posible con poco tiempo restante.'},{t:'Baja: es un solo pedido',p:0,f:'Un pedido de campaña con una hora de margen no es de baja prioridad.'},{t:'Media: se ve después del almuerzo',p:1,f:'La urgencia no depende del horario de almuerzo.'}]},
{q:'Antes de cancelar, ¿qué haces?',o:[{t:'Búsqueda ampliada acotada y conteo puntual; si no aparece, evaluar reasignar a otra tienda o sustituir según las reglas',p:2,f:'Es el orden correcto: buscar, confirmar, reasignar o sustituir y solo al final cancelar.'},{t:'Esperar a que el turno siguiente lo busque',p:0,f:'Con una hora de SLA, esperar es perder el pedido.'},{t:'Marcarlo como entregado y resolverlo después',p:0,f:'Falsear un estado rompe la confianza en los reportes.'}]},
{q:'¿Cómo cierras?',o:[{t:'Registrar la causa raíz (por ejemplo, stock desalineado), ajustar el inventario, comunicar la nueva promesa o cancelación y cerrar',p:2,f:'Un cierre completo alimenta el análisis de recurrencia.'},{t:'Cerrar sin causa para ganar tiempo',p:0,f:'Sin causa no hay análisis: el problema volverá.'},{t:'Avisar al cliente solo si reclama',p:0,f:'Comunicar proactivamente evita reclamos.'}]}],
cierre:'<p><b>Resumen del razonamiento:</b> registrar, clasificar por causa probable, priorizar por daño y tiempo, agotar alternativas (buscar, reasignar, sustituir), comunicar y cerrar con causa raíz. Ese es el hilo del módulo entero.</p>'}]},
quiz:[
{q:'Severidad y prioridad…',o:['Son lo mismo','Son distintas: severidad es el daño y prioridad es el orden de atención','La prioridad no depende del tiempo','La severidad solo la define el cliente'],a:1,w:'La prioridad combina severidad y urgencia.'},
{q:'¿Por qué es clave cerrar una incidencia con causa raíz?',o:['Por formalidad','Porque permite detectar recurrencias y actuar sobre el origen','Para que aparezca cerrada','Para reducir el aging'],a:1,w:'Sin causa, el análisis posterior no es posible.'},
{q:'¿Qué haces antes de cancelar por producto sin ubicar?',o:['Cancelar de inmediato','Buscar, confirmar, reasignar o sustituir según reglas','Esperar al día siguiente','Cambiar el estado a entregado'],a:1,w:'La cancelación es el último recurso.'}],
src:[['https://help.vtex.com/en/docs/tutorials/order-flow-and-status','VTEX Help Center: estados del pedido y cancelación']],
ver:['El ciclo de etapas es práctica general de gestión de incidencias, sin norma. Los SLA de resolución y las categorías de tipo los define cada empresa.','Caso y cifras ficticios.']},

{id:'6.2',title:'Catálogo de excepciones: 24 situaciones que sí ocurren',min:20,
goal:'Analizar 24 excepciones frecuentes con el mismo esquema: causa probable, impacto, qué investigar, responsable, KPI y acción.',
body:`<p>Una excepción es cualquier caso que sale del flujo normal (pedido, picking, despacho, entrega). Cada una se analiza igual: <b>causa probable → impacto → qué investigar → responsable → KPI afectado → acción inmediata</b>. Ese esquema es el que un entrevistador espera cuando pregunta «¿qué harías si…?».</p>
<p>Usa el catálogo de dos formas. Primero, en <b>modo práctica</b>: lee solo el título, piensa tu respuesta en voz alta y revela cada campo. Después, filtra por categoría y repasa las que fallaste. Recuerda que en cada empresa las áreas se llaman distinto y el responsable puede variar: lo que importa es el razonamiento.</p>
<p>Cuidado con dos errores frecuentes: tratar el síntoma como causa (cancelar porque «no hay stock», sin preguntar por qué el sistema decía que sí había) y no dejar registrado el motivo, lo que impide ver patrones después.</p>`,
example:`<p>«Retail Andino» (ficticio) nota que «producto no encontrado» aparece siempre en Surco y en Tecnología. Al revisar la excepción con el esquema de arriba, el equipo pasa de «cancelar el pedido» a «revisar recepciones y ajustes de ese SKU». Es el hilo del caso final del curso base.</p>`,
ex:{type:'cat',intro:'Elige una categoría o mira todas. Activa el modo práctica para entrenar.',items:[
{cat:'Pedido',t:'Pedido duplicado',causa:'Doble clic del cliente, reintento de pago o error de integración.',impacto:'Doble reserva de stock y riesgo de cobro doble.',invest:['Mismo cliente, mismo pago y misma hora','Si hay uno o dos cobros','Si ambos pedidos avanzaron'],resp:'Servicio al cliente',apoyo:'Finanzas',kpi:'Cancelación',accion:'Contactar al cliente, cancelar el duplicado y liberar la reserva.'},
{cat:'Pedido',t:'Pedido detenido en un estado',causa:'Integración caída, tienda sin confirmar inicio o falta de personal.',impacto:'Riesgo de incumplir la promesa.',invest:['Antigüedad en estado','Si hay más pedidos igual en la misma tienda','Confirmación de inicio de atención'],resp:'Operaciones / tienda',apoyo:'TI / sistemas',kpi:'Aging',accion:'Confirmar con la tienda y, si son muchos, escalar como incidente.'},
{cat:'Pedido',t:'Pedido sin reserva de stock',causa:'Falla entre OMS y plataforma o reserva vencida.',impacto:'Puede venderse el mismo stock a otro cliente.',invest:['Estado de la reserva','Hora del pago','Stock del SKU'],resp:'TI / sistemas',apoyo:'Inventario',kpi:'Cancelación',accion:'Reservar manualmente si se puede y escalar la causa.'},
{cat:'Pedido',t:'Pedido parcialmente disponible',causa:'Stock insuficiente en el nodo asignado.',impacto:'Pedido incompleto y baja de Fill Rate.',invest:['Stock por nodo','Si otra tienda lo completa','Reglas de pedido dividido'],resp:'Operaciones / tienda',apoyo:'Inventario',kpi:'Fill Rate',accion:'Reasignar o dividir según reglas y avisar al cliente.'},
{cat:'Pedido',t:'Cancelación por operación (no por el cliente)',causa:'Sin stock, sin cobertura o sin capacidad.',impacto:'Reclamo y pérdida de venta.',invest:['Motivo registrado','SKU y tienda','Si ya pasó antes'],resp:'Operaciones / tienda',apoyo:'Servicio al cliente',kpi:'Cancelación',accion:'Registrar el motivo real y comunicar al cliente con alternativa.'},
{cat:'Stock',t:'Producto no encontrado en picking',causa:'Stock desalineado, mal ubicado o hurto.',impacto:'Cancelación o retraso.',invest:['Stock sistema frente al físico','Últimos movimientos y recepciones','Otras ubicaciones'],resp:'Inventario',apoyo:'Operaciones / tienda',kpi:'Cancelación',accion:'Búsqueda acotada, conteo puntual, reasignar y ajustar.'},
{cat:'Stock',t:'Cantidad insuficiente',causa:'Diferencia de inventario o venta de caja.',impacto:'Pedido incompleto.',invest:['Stock físico','Ventas de POS recientes','Reservas activas'],resp:'Inventario',apoyo:'Operaciones / tienda',kpi:'Fill Rate',accion:'Entregar lo disponible con aviso, o reasignar el faltante.'},
{cat:'Stock',t:'Stock negativo o desactualizado',causa:'Ajustes tardíos o movimientos sin registrar.',impacto:'Sobreventa.',invest:['Último ajuste','Movimientos sin cerrar','Sincronización'],resp:'Inventario',apoyo:'TI / sistemas',kpi:'Exactitud de inventario',accion:'Conteo y ajuste con hora; pausar publicación si es un SKU crítico.'},
{cat:'Stock',t:'SKU o variante incorrecta',causa:'EAN mal cargado o error de picking.',impacto:'Producto equivocado al cliente.',invest:['EAN del SKU','Escaneo en picking','Ficha del producto'],resp:'E-commerce / catálogo',apoyo:'Operaciones / tienda',kpi:'Reclamos',accion:'Corregir el dato y reforzar el escaneo.'},
{cat:'Stock',t:'Reserva que no se libera',causa:'Pedido cancelado sin liberar reserva.',impacto:'Stock disponible bajo el real, ventas perdidas.',invest:['Reservas sin pedido activo','Cancelaciones recientes','Proceso de liberación'],resp:'Inventario',apoyo:'TI / sistemas',kpi:'Disponibilidad',accion:'Liberar reservas huérfanas y revisar el proceso.'},
{cat:'Pago',t:'Pago rechazado',causa:'Fondos, datos, límite o antifraude.',impacto:'Pedido cancelado por pago.',invest:['Motivo del rechazo','Si el cliente reintentó','Ventana de pago'],resp:'Finanzas',apoyo:'Servicio al cliente',kpi:'Cancelación por pago',accion:'Avisar y ofrecer otro método; liberar la reserva si expira.'},
{cat:'Pago',t:'Pago pendiente prolongado',causa:'Confirmación demorada del proveedor de pago.',impacto:'Stock reservado sin certeza de venta.',invest:['Tiempo en pendiente','Política de expiración','Estado en el proveedor de pago'],resp:'Finanzas',apoyo:'TI / sistemas',kpi:'Aging',accion:'Monitorear hasta el plazo y liberar la reserva si expira.'},
{cat:'Pago',t:'Pago confirmado pero pedido no creado',causa:'Falla de integración entre pasarela y plataforma.',impacto:'Cliente cobró sin pedido.',invest:['ID de transacción','Si el pedido existe en el OMS','Registros de integración'],resp:'TI / sistemas',apoyo:'Finanzas',kpi:'Reclamos',accion:'Escalar con ID de transacción y hora; avisar al cliente.'},
{cat:'Logística',t:'Pedido preparado sin ruta asignada',causa:'Corte tardío o falla del TMS.',impacto:'Retraso de despacho.',invest:['Hora del corte','Estado en el TMS','Capacidad de la ruta'],resp:'Logística / transporte',apoyo:'Operaciones / tienda',kpi:'On Time',accion:'Asignar ruta o reprogramar y avisar.'},
{cat:'Logística',t:'Retraso de despacho',causa:'Capacidad, tráfico o falta de vehículo.',impacto:'Entrega fuera de la promesa.',invest:['Franja y capacidad','Ruta y paradas','Reportes del operador'],resp:'Logística / transporte',apoyo:'Operaciones / tienda',kpi:'On Time',accion:'Priorizar los que vencen, reprogramar y avisar.'},
{cat:'Logística',t:'Cliente ausente',causa:'Sin aviso previo o franja mal elegida.',impacto:'Entrega fallida y costo de reintento.',invest:['Intentos previos','Datos de contacto','Franja prometida'],resp:'Logística / transporte',apoyo:'Servicio al cliente',kpi:'Éxito al primer intento',accion:'Contactar y reprogramar con confirmación.'},
{cat:'Logística',t:'Dirección incorrecta o incompleta',causa:'Falta de referencia o error al digitar.',impacto:'Fallo de entrega.',invest:['Dirección y referencia','Historial del cliente','Cobertura'],resp:'Servicio al cliente',apoyo:'Logística / transporte',kpi:'Éxito al primer intento',accion:'Confirmar la dirección con el cliente antes de la ruta.'},
{cat:'Logística',t:'Pedido perdido o extraviado',causa:'Falla de trazabilidad o robo.',impacto:'Reposición o reembolso.',invest:['Último estado y prueba de entrega','Ruta y repartidor','Reclamo al operador'],resp:'Logística / transporte',apoyo:'Finanzas',kpi:'Reclamos',accion:'Abrir reclamo al operador y reponer o reembolsar.'},
{cat:'Postventa',t:'Producto equivocado entregado',causa:'Error de picking o EAN incorrecto.',impacto:'Cambio y logística inversa.',invest:['Pedido frente a lo enviado','Escaneo','Picker o turno'],resp:'Operaciones / tienda',apoyo:'Servicio al cliente',kpi:'Tasa de error',accion:'Cambio prioritario y análisis de causa.'},
{cat:'Postventa',t:'Producto dañado en entrega',causa:'Embalaje o manejo.',impacto:'Cambio, reembolso y mala experiencia.',invest:['Fotos','Embalaje','Ruta y repartidor'],resp:'Servicio al cliente',apoyo:'Logística / transporte',kpi:'Reclamos',accion:'Aceptar el reclamo con evidencia y coordinar el cambio.'},
{cat:'Postventa',t:'Devolución con reembolso pendiente',causa:'Falta de inspección o aprobación.',impacto:'Reclamo y riesgo por plazo.',invest:['Estado de la devolución','Quién aprueba','Plazo comprometido'],resp:'Finanzas',apoyo:'Servicio al cliente',kpi:'Reclamos',accion:'Acelerar la aprobación y comunicar la fecha.'},
{cat:'Sistemas y catálogo',t:'Error de precio en la web',causa:'Carga manual o regla de promoción mal configurada.',impacto:'Pedidos a precio erróneo y pérdida.',invest:['Precio frente a la lista','Hora de cambio','Pedidos ya creados'],resp:'E-commerce / catálogo',apoyo:'Comercial / compras',kpi:'Margen',accion:'Corregir de inmediato y definir qué hacer con los pedidos.'},
{cat:'Sistemas y catálogo',t:'Error de catálogo o de atributos',causa:'Ficha desactualizada o EAN mal asignado.',impacto:'Devoluciones o errores de picking.',invest:['Atributos y EAN','Imágenes y variantes','Reclamos del SKU'],resp:'E-commerce / catálogo',apoyo:'Comercial / compras',kpi:'Devoluciones',accion:'Corregir la ficha y avisar a las áreas afectadas.'},
{cat:'Sistemas y catálogo',t:'Error en el comprobante (boleta o factura)',causa:'Datos del cliente mal ingresados.',impacto:'Problemas contables y reclamos.',invest:['Datos del comprobante','Pedido original','Si ya se envió'],resp:'Finanzas',apoyo:'Servicio al cliente',kpi:'Pedidos sin comprobante',accion:'Corregir con el documento que corresponda (capítulo 5.1).'}]},
quiz:[
{q:'¿Cuál es el error frecuente al tratar una excepción?',o:['Registrarla','Tratar el síntoma como causa y no dejar el motivo registrado','Asignar responsable','Medir el KPI'],a:1,w:'Sin causa registrada no hay análisis.'},
{q:'El esquema de una excepción incluye…',o:['Solo la solución','Causa, impacto, qué investigar, responsable, KPI y acción','Solo el responsable','Solo el KPI'],a:1,w:'Es el razonamiento completo.'},
{q:'En el modo práctica, conviene…',o:['Revelar todo de inmediato','Pensar la respuesta antes de revelar cada campo','Saltar los difíciles','Memorizar sin pensar'],a:1,w:'La recuperación activa fija mejor lo aprendido.'}],
src:[['https://help.vtex.com/en/docs/tutorials/order-flow-and-status','VTEX Help Center: estados y reservas']],
ver:['Las causas, responsables y acciones son una guía de razonamiento; en tu empresa las áreas y las reglas pueden variar.','Ningún dato de este catálogo es de una empresa real.']},

{id:'6.3',title:'Diagnóstico de stock: sistema, reservado y físico',min:20,
goal:'Leer tres o cuatro números de stock y deducir qué está pasando: stock fantasma, sobreventa, reserva colgada o mercadería sin ingresar.',
body:`<p>Los reportes de stock casi siempre muestran varios números a la vez. Aprende a leerlos <b>como un patrón</b>:</p>
<ul><li><b>Sistema</b>: lo que dice el OMS o el ERP.</li><li><b>Reservado</b>: lo comprometido a pedidos.</li><li><b>Disponible mostrado</b>: sistema menos reservado (según la regla de la empresa).</li><li><b>Físico</b>: lo que hay en la ubicación.</li></ul>
${T(['Patrón','Diagnóstico probable','Qué haces'],[
['Sistema alto, físico mucho menor','Stock fantasma (merma, hurto, error de recepción)','Conteo y ajuste; pausar el SKU si es crítico'],
['Reservado mayor que el físico','Sobreventa: se prometió más de lo que existe','Reasignar, sustituir o cancelar con aviso'],
['Físico alto, disponible online cero','Sincronización atrasada o bloqueo indebido','Revisar bloqueos y la última sincronización'],
['Físico mayor que el sistema','Mercadería sin ingresar (recepción o putaway pendiente)','Registrar el ingreso y ajustar'],
['Reservas con pocos pedidos activos','Reserva colgada (no se liberó)','Liberar reservas huérfanas y revisar el proceso'],
['Todos los números cuadran','Consistente','Ninguna']])}
<p>Recuerda que un mismo caso puede tener dos lecturas (por ejemplo, stock fantasma que provoca sobreventa). Empieza por la <b>causa</b> que explique la mayor diferencia y luego mira las consecuencias.</p>`,
example:`<p>En «Retail Andino» (ficticio), un SKU muestra sistema 5, reservado 3 y físico 1. El sistema ofrece 2 unidades, pero solo hay 1 en la tienda y ya hay 3 reservadas: tres clientes recibirán un correo de cancelación. La causa es la diferencia de 4 unidades sin explicar.</p>`,
ex:{type:'match',intro:'¿Qué diagnóstico corresponde?',opts:['Stock fantasma','Sobreventa','Sincronización o bloqueo','Mercadería sin ingresar','Reserva colgada','Consistente'],items:[
{t:'Sistema 5, reservado 3, físico 1',a:'Stock fantasma'},
{t:'Sistema 10, reservado 7, disponible mostrado 3, físico 6',a:'Sobreventa'},
{t:'Sistema 8, reservado 0, disponible mostrado 0, físico 8',a:'Sincronización o bloqueo'},
{t:'Sistema 2, reservado 0, físico 6',a:'Mercadería sin ingresar'},
{t:'Sistema 6, reservado 4, físico 6, y solo 1 pedido activo del SKU',a:'Reserva colgada'},
{t:'Sistema 12, reservado 3, disponible mostrado 9, físico 12',a:'Consistente'}],
sol:'<p>Correcto. En el primero, la diferencia de 4 unidades entre sistema y físico es la causa; la sobreventa es la consecuencia. En el segundo, las reservas (7) superan lo que hay físicamente (6).</p>',
also:{type:'calc',intro:'Tres SKU con (sistema, reservado, físico): A (5, 3, 1), B (10, 7, 6) y C (12, 3, 12). Unidades vendibles reales = máx(0, físico − reservado). El sistema ofrece: sistema − reservado.',task:'Calcula las unidades vendibles reales, las que el sistema ofrece y la diferencia (riesgo de sobreventa).',
parts:[{l:'Unidades vendibles reales',tol:0,fn:function(){return [[5,3,1],[10,7,6],[12,3,12]].reduce(function(a,x){return a+Math.max(0,x[2]-x[1])},0)}},{l:'Unidades que ofrece el sistema',tol:0,fn:function(){return [[5,3,1],[10,7,6],[12,3,12]].reduce(function(a,x){return a+(x[0]-x[1])},0)}},{l:'Riesgo de sobreventa',u:'uds',tol:0,fn:function(){var r=[[5,3,1],[10,7,6],[12,3,12]];return r.reduce(function(a,x){return a+(x[0]-x[1])},0)-r.reduce(function(a,x){return a+Math.max(0,x[2]-x[1])},0)}}],
sol:function(v){return '<p>Reales: A = máx(0, 1−3) = 0, B = máx(0, 6−7) = 0, C = 12−3 = 9 → <b>'+v[0]+'</b>. El sistema ofrece 2 + 3 + 9 = <b>'+v[1]+'</b>. Diferencia = <b>'+v[2]+'</b> unidades prometidas que no existen, concentradas en A y B.</p>'}}},
quiz:[
{q:'Sistema 2, reservado 0, físico 6 sugiere…',o:['Stock fantasma','Mercadería sin ingresar al sistema','Sobreventa','Reserva colgada'],a:1,w:'El físico supera al sistema: falta registrar el ingreso.'},
{q:'Reservado mayor que el físico es señal de…',o:['Sobreventa','Consistencia','Ingreso pendiente','Sincronización perfecta'],a:0,w:'Se prometió más de lo que existe.'},
{q:'¿Qué buscas primero en un caso con dos lecturas posibles?',o:['La consecuencia','La causa que explique la mayor diferencia','El precio','El nombre del picker'],a:1,w:'Corregir la causa evita que se repita.'}],
src:[['https://help.vtex.com/en/docs/tutorials/order-flow-and-status','VTEX: reservas e inventario']],
ver:['Cómo se calcula el «disponible mostrado» depende de la regla de cada empresa (capítulo 2.5).','Todas las cifras son ficticias.']},

{id:'6.4',title:'¿Dónde investigo? Casos por sistema y por KPI',min:20,
goal:'Seguir un pedido por el flujo de sistemas para ubicar el último punto donde existe el dato, y diagnosticar un KPI que empeora.',
body:`<p>Antes de investigar, ten en mente el recorrido: <b>plataforma → pago → OMS (pedido, reserva, asignación) → WMS o tienda (picking) → ERP (comprobante) → TMS u operador (ruta y entrega) → cliente</b>. La regla es simple: <b>sigue el pedido de izquierda a derecha y encuentra el último sistema donde el dato existe</b>. El problema está justo después.</p>
<ul><li>¿Pagó? Mira la pasarela y el estado de pago.</li><li>¿Se creó el pedido? Mira el OMS.</li><li>¿Tiene reserva y asignación? Mira el OMS y la tienda.</li><li>¿Llegó al picking? Mira el WMS o la app de tienda.</li><li>¿Tiene comprobante? Mira el ERP o el OMS.</li><li>¿Tiene ruta y entrega? Mira el TMS o el operador.</li></ul>
<h3>Cuando lo que empeora es un KPI</h3>
<p>Ante «la cancelación pasó de 3% a 7%», sigue este orden: <b>1)</b> verifica definición, denominador y período; <b>2)</b> segmenta por tienda, categoría, motivo, canal y día; <b>3)</b> busca concentración; <b>4)</b> formula una hipótesis y cómo confirmarla; <b>5)</b> propón una acción con responsable. Es el método del caso final.</p>`,
example:`<p>Un cliente de «Retail Andino» (ficticio) pagó y no recibe nada. En el OMS el pedido existe en «Payment approved» pero sin asignación a tienda. El último punto con dato es el OMS y el fallo está entre el OMS y la tienda: se escala con ese dato exacto, no con «el pedido no funciona».</p>`,
ex:{type:'scenario',intro:'Tres casos. Cada paso te pide decidir dónde mirar y por qué.',cases:[
{t:'Pago confirmado, sin pedido en preparación',sit:'<p>Un cliente pagó hace 40 minutos y su pedido no aparece en la lista de preparación de la tienda.</p>',steps:[
{q:'¿Dónde investigas primero?',o:[{t:'En la plataforma y el OMS: verificar si el pedido se creó y en qué estado está',p:2,f:'El pago llega antes; el siguiente punto es el pedido en el OMS.'},{t:'En el TMS, porque quizá ya salió a ruta',p:0,f:'Sin preparación no puede haber ruta.'},{t:'En Power BI, para ver la tendencia',p:1,f:'Sirve para saber si hay más casos, pero no para localizar este.'}]},
{q:'¿Qué verificas?',o:[{t:'Si el pedido existe, si tiene reserva y si se asignó a una tienda',p:2,f:'Es el recorrido del dato a lo largo del OMS.'},{t:'Solo el estado del pago',p:1,f:'Ya está confirmado: hay que avanzar.'},{t:'Si el cliente tiene deudas',p:0,f:'No tiene relación con el problema.'}]},
{q:'Encuentras el pedido en «Payment approved», sin asignación. ¿Qué haces?',o:[{t:'Escalar a TI o e-commerce con pedido, hora, estado y evidencia, y mientras coordinar con la tienda para atenderlo',p:2,f:'Entregas datos concretos y proteges la promesa al cliente.'},{t:'Cancelar y pedirle que compre de nuevo',p:0,f:'Empeoras la experiencia por un problema que no es del cliente.'},{t:'Esperar a ver si se corrige solo',p:0,f:'Sin acción, el SLA se consume.'}]}],
cierre:'<p><b>Cadena de verificación:</b> pago confirmado → ¿pedido creado? → ¿reserva? → ¿asignación? → ¿llegó a picking?. El fallo estaba entre la asignación y la tienda.</p>'},
{t:'Pedido 8 horas en «Ready for handling»',sit:'<p>El pedido está en «Ready for handling» hace 8 horas y su promesa vence hoy.</p>',steps:[
{q:'¿Cuál es tu primera verificación?',o:[{t:'Si la tienda confirmó el inicio de atención',p:2,f:'En VTEX, el pedido no avanza hasta que se confirma que la atención empezó.'},{t:'Cambiar el estado a facturado manualmente',p:0,f:'Saltar estados rompe la trazabilidad.'},{t:'Llamar al cliente para avisarle',p:1,f:'Puede hacer falta luego, pero antes debes saber qué pasa.'}]},
{q:'¿Es un caso aislado o masivo?',o:[{t:'Busco otros pedidos igual en la misma tienda para ver si hay causa común',p:2,f:'Muchos pedidos iguales suelen indicar falta de personal o integración.'},{t:'Asumo que es aislado',p:0,f:'Podrías perder el patrón.'},{t:'Espero al cierre del día',p:0,f:'Para entonces la promesa ya venció.'}]},
{q:'Hay 14 pedidos así en la misma tienda. ¿Qué haces?',o:[{t:'Escalar como incidente al responsable de tienda y TI, con la lista y las horas',p:2,f:'Es una causa común: tienda sin picker o integración.'},{t:'Tratarlos uno por uno',p:0,f:'Pierdes tiempo y no resuelves la causa.'},{t:'Cancelarlos',p:0,f:'Solo como último recurso.'}]}],
cierre:'<p><b>Regla:</b> agrupa antes de resolver. Catorce pedidos con el mismo síntoma son un problema, no catorce.</p>'},
{t:'La cancelación pasó de 3% a 7%',sit:'<p>Tu jefe pregunta por qué la cancelación pasó de 3% a 7% en dos semanas.</p>',steps:[
{q:'¿Qué haces primero?',o:[{t:'Verificar la definición, el denominador y el período comparado',p:2,f:'Un cambio de definición puede explicar la diferencia.'},{t:'Culpar a la tienda con más cancelaciones',p:0,f:'Sin segmentar, puedes equivocarte de tienda.'},{t:'Pedir más personal',p:0,f:'No tienes evidencia de que falte gente.'}]},
{q:'¿Cómo segmentas?',o:[{t:'Por tienda, categoría, motivo, canal y día',p:2,f:'Busca dónde se concentra el aumento.'},{t:'Solo por mes',p:0,f:'Es un corte demasiado grueso.'},{t:'Por color del producto',p:0,f:'No es un corte útil para este KPI.'}]},
{q:'Encuentras que casi todo el aumento está en una tienda y una categoría, con el motivo «producto sin ubicar». ¿Qué hipótesis planteas?',o:[{t:'Stock desalineado en esos SKU; lo confirmo con conteo físico y con la hora de los ajustes',p:2,f:'Formulas una hipótesis y cómo confirmarla, sin afirmarla como hecho.'},{t:'El cliente ya no quiere comprar',p:0,f:'Los motivos indican otra cosa.'},{t:'Es mala suerte',p:0,f:'Las concentraciones no son suerte.'}]}],
cierre:'<p><b>Método:</b> definición → segmentación → concentración → hipótesis verificable → acción con responsable. Es el método del caso final del curso base.</p>'}]},
quiz:[
{q:'Para ubicar un fallo en el flujo, buscas…',o:['El sistema más grande','El último punto donde existe el dato','El primero que falle','El más barato'],a:1,w:'El problema está justo después de ese punto.'},
{q:'14 pedidos con el mismo síntoma indican…',o:['14 problemas','Un problema con causa común','Suerte','Un error del cliente'],a:1,w:'Agrupa antes de resolver.'},
{q:'Ante un KPI que empeora, el primer paso es…',o:['Contratar más gente','Verificar definición, denominador y período','Cambiar el objetivo','Ignorarlo'],a:1,w:'Evita diagnosticar un cambio que es de medición.'}],
src:[['https://help.vtex.com/en/docs/tutorials/order-flow-and-status','VTEX Help Center: estados del pedido y confirmación de atención']],
ver:['El recorrido de sistemas es un modelo; en tu empresa los nombres y las integraciones pueden variar.','Casos ficticios.']},

{id:'6.5',title:'Priorización y SLA operativo',min:20,
goal:'Calcular el tiempo restante de cada pedido y ordenar la atención por vencimiento, impacto e incidencias, aplicando gestión por excepciones.',
body:`<p>Con 100 pedidos pendientes no miras los 100: miras <b>los que salen del umbral</b> (gestión por excepciones). Para eso necesitas tres datos por pedido: <b>antigüedad</b> (cuánto lleva en el estado), <b>SLA</b> (tiempo total permitido) y <b>tiempo restante = SLA − antigüedad</b>.</p>
<h3>Regla de priorización</h3>
<ol><li><b>Vencidos o por vencer:</b> menor tiempo restante primero (vencidos, tiempo restante ≤ 0, se atienden y se reportan).</li><li><b>Impacto:</b> campaña, pedido de alto valor o cliente con reclamo abierto.</li><li><b>Incidencia bloqueante:</b> los que no avanzan sin intervención.</li><li><b>Resolución rápida:</b> a igualdad, los que se resuelven en minutos.</li></ol>
<p>Ante un empate, el criterio es de negocio. Lo importante es que puedas <b>explicar por qué</b> atiendes uno antes que otro. Los umbrales y los SLA los define cada empresa ${V('umbrales y SLA de tu empresa')}.</p>`,
example:`<p>Son las 10:00 en «Retail Andino» (ficticio): 85 pedidos pendientes, 12 vencen hoy, 7 con producto no encontrado. Los 12 que vencen y, dentro de ellos, los 7 con incidencia forman tu lista corta; el resto se monitorea.</p>`,
ex:{type:'calc',intro:'Ocho pedidos (datos sintéticos). Tiempo restante = SLA total − antigüedad. Vencido: tiempo restante ≤ 0. En riesgo: entre 0 y 2 horas.',cols:['Pedido','Antigüedad (h)','SLA total (h)','Incidencia'],rows:[['P1',3,8,'No'],['P2',6,8,'No'],['P3',9,8,'Sí'],['P4',1,4,'No'],['P5',5,6,'Sí'],['P6',2,24,'No'],['P7',7,8,'No'],['P8',4,4,'No']],num:[1,2],
task:'Calcula cuántos pedidos están vencidos, cuántos en riesgo (más de 0 y hasta 2 h restantes) y el menor tiempo restante entre los que aún no vencen.',
parts:[{l:'Pedidos vencidos',tol:0,fn:function(r){return r.filter(function(x){return x[2]-x[1]<=0}).length}},{l:'Pedidos en riesgo',tol:0,fn:function(r){return r.filter(function(x){var t=x[2]-x[1];return t>0&&t<=2}).length}},{l:'Menor tiempo restante (no vencidos)',u:'h',tol:0,fn:function(r){return Math.min.apply(null,r.map(function(x){return x[2]-x[1]}).filter(function(t){return t>0}))}}],
sol:function(v){return '<p>Restantes: P1 5, P2 2, P3 −1, P4 3, P5 1, P6 22, P7 1, P8 0. Vencidos: P3 y P8 = <b>'+v[0]+'</b>. En riesgo: P2 (2), P5 (1) y P7 (1) = <b>'+v[1]+'</b>. El menor restante entre los que aún no vencen es <b>'+v[2]+' h</b>.</p>'},
also:{type:'reveal',task:'P5 y P7 tienen 1 hora restante. P5 tiene una incidencia y P7 no. ¿A cuál atiendes primero y por qué?',sol:'<p>Una respuesta defendible: <b>P5</b>, porque tiene incidencia bloqueante y necesita más tiempo para resolverse; si no se empieza ya, es el que más probablemente vencerá. P7 probablemente solo requiere despacho y se puede resolver en minutos <i>después</i>. Si P7 tuviera un cliente crítico o de campaña, el criterio de impacto podría cambiar el orden. Lo importante es explicar el criterio.</p>'}},
quiz:[
{q:'Tiempo restante =',o:['Antigüedad − SLA','SLA − antigüedad','SLA × antigüedad','Antigüedad + SLA'],a:1,w:'Si es 0 o negativo, el pedido está vencido.'},
{q:'Gestión por excepciones significa…',o:['Mirar todos los pedidos','Mirar los que salen del umbral','Ignorar los pedidos','Cancelar los tardíos'],a:1,w:'Concentras el esfuerzo donde hay riesgo.'},
{q:'A igualdad de tiempo restante, el criterio de negocio incluye…',o:['El azar','Impacto e incidencias bloqueantes','El nombre del cliente','La hora del almuerzo'],a:1,w:'Y debes poder explicar la decisión.'}],
src:[['https://help.vtex.com/en/docs/tutorials/order-flow-and-status','VTEX: estados y antigüedad de los pedidos']],
ver:['Reglas de priorización y umbrales: los de tu empresa. Los del ejercicio son un modelo didáctico.','Datos sintéticos.']},

{id:'6.6',title:'¿A quién escalo? Coordinación entre áreas',min:20,
goal:'Elegir responsable probable y apoyo para cada problema, y armar un mensaje de escalamiento con la información necesaria.',
body:`<p>Escalar bien es un oficio: no basta con «avisar». Un buen escalamiento indica <b>a quién</b> (área responsable probable), <b>a quién más</b> (apoyo), <b>qué información entregas</b> y <b>por qué</b>. Si mandas «hay un problema con los pedidos», la otra área pierde tiempo preguntando. Si mandas datos, puede actuar.</p>
<p>En cada empresa las responsabilidades cambian; por eso aquí aprendes el razonamiento: ¿quién controla la causa probable? ¿quién puede ayudar a confirmarla? Las áreas del ejercicio son un modelo genérico.</p>
<h3>Estructura de un mensaje de escalamiento</h3>
<ol><li><b>Qué pasó</b> (una frase).</li><li><b>Desde cuándo y cuánto afecta</b> (pedidos, tienda, SKU, horas).</li><li><b>Qué ya revisaste.</b></li><li><b>Qué necesitas</b> y <b>para cuándo</b>.</li><li><b>Evidencia</b> (números de pedido, capturas).</li></ol>`,
example:`<p>Un mensaje flojo: «Hay pedidos atorados». Uno bueno: «Desde las 8:30, 14 pedidos de tienda Surco llevan más de 4 h en Ready for handling. La tienda confirma personal completo. Necesito revisar la integración antes de las 12:00. Adjunto la lista.»</p>`,
ex:{type:'route',intro:'Para cada problema, elige el responsable probable y el apoyo. Luego comprueba.',areas:AREAS,items:[
{t:'El stock del sistema no coincide con el físico',r:['Inventario','Operaciones / tienda'],a:['Operaciones / tienda','Inventario'],info:'SKU, ubicación, stock sistema, físico, reservas y últimos movimientos.',why:'Inventario controla el registro; la tienda confirma lo físico.'},
{t:'Pedido asignado pero sin preparar en la tienda',r:['Operaciones / tienda'],a:['Inventario','TI / sistemas'],info:'Pedido, hora de asignación, estado y personal disponible.',why:'La tienda controla el picking; TI ayuda si es un problema de integración.'},
{t:'Retraso del transportista en una zona',r:['Logística / transporte'],a:['Operaciones / tienda','Servicio al cliente'],info:'Ruta, zona, pedidos afectados y horas de retraso.',why:'Logística gestiona al operador; servicio al cliente avisa a los clientes.'},
{t:'Pago aprobado pero el pedido no existe',r:['TI / sistemas','Finanzas'],a:['Finanzas','TI / sistemas'],info:'ID de transacción, hora y monto.',why:'Es una falla de integración con impacto en cobros.'},
{t:'Cliente reclama por un pedido tardío',r:['Servicio al cliente'],a:['Operaciones / tienda','Logística / transporte'],info:'Fechas de promesa y entrega, estado, motivo del retraso.',why:'Servicio al cliente responde; necesita la evidencia de operación.'},
{t:'Error en la boleta o factura emitida',r:['Finanzas'],a:['Servicio al cliente','TI / sistemas','Operaciones / tienda'],info:'Comprobante, pedido, datos correctos y datos erróneos.',why:'La corrección documentaria es de Finanzas.'},
{t:'Producto de alta demanda agotado en la web',r:['Comercial / compras','Inventario'],a:['Inventario','Comercial / compras'],info:'SKU, demanda diaria, stock, lead time del proveedor.',why:'La reposición se decide con compras y se controla con inventario.'},
{t:'Precio o atributos incorrectos en la ficha',r:['E-commerce / catálogo'],a:['Comercial / compras','TI / sistemas'],info:'SKU, dato incorrecto, dato correcto, pedidos afectados.',why:'Catálogo gestiona la ficha; comercial valida precio.'}],
also:{type:'reveal',task:'Escribe un mensaje de escalamiento para el primer problema (stock del sistema distinto del físico).',sol:'<p><b>Ejemplo:</b> «Inventario: en tienda Surco, el SKU TV-55 figura con 5 unidades en sistema y hay 1 físicamente (conteo de hoy 13:10). Hay 3 unidades reservadas y 3 pedidos en riesgo. Ya revisé ubicaciones alternas y la última recepción del 12/9. Necesito confirmar si hubo una recepción sin ingresar o una merma sin registrar y ajustar antes de las 16:00. Adjunto los 3 números de pedido.»</p>'}},
quiz:[
{q:'Un buen escalamiento incluye…',o:['Solo «hay un problema»','Qué pasó, alcance, qué revisaste, qué necesitas y para cuándo','Solo el número del pedido','Solo una queja'],a:1,w:'La otra área puede actuar sin preguntar.'},
{q:'Las áreas responsables de un problema…',o:['Son idénticas en todas las empresas','Pueden variar; importa el razonamiento','No existen','Siempre es Finanzas'],a:1,w:'Aprende a pensar quién controla la causa.'},
{q:'Un pago aprobado sin pedido creado se escala primero a…',o:['Servicio al cliente','TI / sistemas, con apoyo de Finanzas','Marketing','Nadie'],a:1,w:'Es una falla de integración con impacto en cobros.'}],
src:[],
ver:['La asignación de responsables es un modelo general: confirma la estructura de tu empresa.','Ejemplos ficticios.']},

{id:'6.7',title:'Devoluciones y postventa, de punta a punta',min:20,
goal:'Recorrer el proceso completo de una devolución y decidir el destino del producto: reingreso, merma, proveedor, cambio o rechazo.',
body:`<p>Una devolución no es solo «restar una venta»: toca <b>inventario, disponibilidad, estado del pedido, cliente y finanzas</b>. Recorre el proceso en el diagrama y toca cada paso.</p>
<p>La decisión clave es la <b>inspección</b>: ¿el producto es apto para volver a venderse? Si es apto, <b>reingresa al stock</b> (y el stock disponible sube). Si no lo es, se registra como <b>merma</b> o se devuelve al proveedor si es un defecto de fábrica cubierto por garantía. Después vienen el <b>reembolso</b> o cambio y el documento correspondiente (nota de crédito, capítulo 5.1).</p>
<p>Las reglas de plazo, estado del producto y reembolso las fija la política de la empresa dentro de lo que permite la norma de protección al consumidor ${V('política de devoluciones y norma aplicable')}.</p>`,
example:`<p>En «Retail Andino» (ficticio), una polera devuelta con etiquetas y sin uso reingresa al stock y vuelve a estar disponible en la web. Una licuadora con motor defectuoso se devuelve al proveedor. Un producto con humedad va a merma. Cada destino cambia el stock y el costo de forma distinta.</p>`,
ex:{type:'flow',intro:'Proceso de devolución (modelo de referencia).',steps:[
{k:'trigger',t:'Solicitud de devolución',d:'El cliente la pide por el canal definido. Se registra con pedido, producto y motivo.'},
{k:'cond',t:'Validación de política',d:'¿Está dentro del plazo y de las condiciones? Si no, se rechaza con explicación.'},
{k:'action',t:'Autorización y recojo o entrega en tienda',d:'Se define cómo regresa el producto y quién lo recibe.'},
{k:'action',t:'Recepción',d:'Se registra la llegada y se verifica que sea el producto correcto.'},
{k:'cond',t:'Inspección',d:'¿Apto para venta? Sí: reingreso. No: merma o devolución al proveedor.'},
{k:'action',t:'Actualización de stock',d:'Reingreso suma al disponible. Merma se registra aparte (capítulo 2.5).'},
{k:'action',t:'Reembolso o cambio',d:'Con nota de crédito u otro documento según el caso (capítulo 5.1).'},
{k:'end',t:'Cierre y análisis',d:'Se registra el motivo para medir la tasa de devolución por SKU y por causa.'}],
also:{type:'match',intro:'¿Cuál es el destino de cada producto devuelto?',opts:['Reingreso a stock','Merma','Devolver al proveedor','Cambio inmediato','Rechazar (fuera de política)'],items:[
{t:'Polera sin uso y con etiquetas',a:'Reingreso a stock'},
{t:'Licuadora con defecto de fábrica, dentro de garantía',a:'Devolver al proveedor'},
{t:'Producto con humedad, no vendible',a:'Merma'},
{t:'El cliente pide cambiar de talla y hay stock',a:'Cambio inmediato'},
{t:'Devolución solicitada fuera del plazo de la política',a:'Rechazar (fuera de política)'}],
sol:'<p>Bien. Cada destino cambia el stock y el costo de forma distinta. Las políticas reales varían.</p>',
also:{type:'calc',intro:'Mes de «Retail Andino» (ficticio): 800 pedidos entregados y 48 devoluciones. De ellas, 40 son aptas y reingresan; 8 van a merma con un costo de S/ 90 por unidad.',task:'Calcula la tasa de devolución, las unidades que reingresan y el costo de la merma.',
parts:[{l:'Tasa de devolución',u:'%',tol:0.1,fn:function(){return 100*48/800}},{l:'Unidades que reingresan',tol:0,fn:function(){return 48-8}},{l:'Costo de la merma',u:'S/',tol:0.01,fn:function(){return 8*90}}],
sol:function(v){return '<p>Tasa = 48/800 = <b>'+fmt(v[0])+'%</b>. Reingresan <b>'+v[1]+'</b> unidades (48 − 8). Merma = 8 × 90 = <b>S/ '+fmt(v[2],0)+'</b>. Si todas las devoluciones fueran mermas, el costo sería seis veces mayor: la inspección importa.</p>'}}}},
quiz:[
{q:'La decisión clave de una devolución es…',o:['El precio','La inspección: ¿el producto es apto para volver a venderse?','El color','El operador'],a:1,w:'De ahí depende el destino y el impacto en stock.'},
{q:'Un producto apto devuelto…',o:['Va a merma','Reingresa al stock y vuelve a estar disponible','Se cancela','Se ignora'],a:1,w:'Aumenta el disponible.'},
{q:'Una devolución impacta en…',o:['Solo el cliente','Inventario, disponibilidad, estado del pedido, cliente y finanzas','Solo Finanzas','Nada'],a:1,w:'Por eso se gestiona como proceso.'}],
src:[['https://cpe.sunat.gob.pe/informacion_general/obligados_cpe','SUNAT: comprobantes de pago electrónicos (nota de crédito)']],
ver:['Plazos, condiciones y reembolsos: política de tu empresa y normativa de protección al consumidor '+V('norma vigente y política interna'),'Datos y costos ficticios.']},

{id:'6.8',title:'Compras y facturas de proveedores',min:20,
goal:'Entender el flujo operativo de una compra a un proveedor y aplicar la conciliación de tres vías (orden de compra, recepción, factura).',
body:`<p>La oferta de un puesto de operaciones e-commerce puede incluir «registrar y hacer seguimiento a facturas de proveedores». No hace falta ser contador: hace falta entender el <b>flujo</b> y qué se controla.</p>
<p><b>Orden de compra (OC) → recepción → factura del proveedor → validación → registro → conformidad → aprobación → pago → seguimiento.</b></p>
<h3>Conciliación de tres vías</h3>
<p>Antes de aprobar una factura se comprueba que <b>lo pedido (OC)</b>, <b>lo recibido</b> y <b>lo facturado</b> coincidan en cantidad, precio y total. La <b>conformidad</b> es la confirmación de que lo recibido corresponde a lo pedido; sin ella, no se aprueba el pago. Las discrepancias se resuelven con el proveedor (corrección, nota de crédito o entrega del faltante).</p>
<p>Las reglas tributarias (datos exigidos en la factura, plazos de registro, retenciones o detracciones) son un tema contable propio: aquí solo aprendes el flujo operativo ${V('reglas tributarias con el área contable y SUNAT')}.</p>`,
example:`<p>«Retail Andino» (ficticio) pide 500 licuadoras a S/ 12 por unidad. Recepción registra 480 y el proveedor factura 500. La factura debe conciliarse contra lo recibido: no se paga por las 20 que faltan hasta resolverlo con el proveedor.</p>`,
ex:{type:'calc',intro:'Orden de compra: 500 unidades a S/ 12. Recepción: 480 unidades. Factura del proveedor: 500 unidades a S/ 12.',task:'Calcula el monto conforme (lo recibido al precio pactado), la diferencia con la factura y el desvío en %.',
parts:[{l:'Monto conforme',u:'S/',tol:0.01,fn:function(){return 480*12}},{l:'Diferencia con la factura',u:'S/',tol:0.01,fn:function(){return 500*12-480*12}},{l:'Desvío sobre la factura',u:'%',tol:0.1,fn:function(){return 100*(500*12-480*12)/(500*12)}}],
sol:function(v){return '<p>Conforme = 480 × 12 = <b>S/ '+fmt(v[0],0)+'</b>. Factura = 6 000. Diferencia = <b>S/ '+fmt(v[1],0)+'</b> (20 unidades × 12), un <b>'+fmt(v[2])+'%</b> de desvío. Se aprueba lo conforme y se gestiona la diferencia con el proveedor.</p>'},
also:{type:'match',intro:'¿Qué acción corresponde?',opts:['Pedir corrección o nota de crédito al proveedor','Conformidad parcial y reclamar el faltante','Rechazar la duplicada y avisar a Finanzas','No aprobar hasta validar el origen'],items:[
{t:'La factura tiene un precio distinto al de la orden de compra',a:'Pedir corrección o nota de crédito al proveedor'},
{t:'Se recibió menos de lo facturado',a:'Conformidad parcial y reclamar el faltante'},
{t:'Llegó la misma factura dos veces',a:'Rechazar la duplicada y avisar a Finanzas'},
{t:'Hay una factura sin orden de compra ni recepción',a:'No aprobar hasta validar el origen'}],
sol:'<p>Bien. El principio común: no se aprueba lo que no se puede conciliar.</p>'}},
quiz:[
{q:'La conciliación de tres vías compara…',o:['Precio, marca y color','Orden de compra, recepción y factura','Cliente, pedido y ruta','Stock, ventas y devoluciones'],a:1,w:'Cantidad, precio y total.'},
{q:'La conformidad es…',o:['El pago','La confirmación de que lo recibido corresponde a lo pedido','Una factura','Un reclamo'],a:1,w:'Sin conformidad no se aprueba el pago.'},
{q:'Factura sin OC ni recepción…',o:['Se paga','No se aprueba hasta validar su origen','Se archiva','Se duplica'],a:1,w:'No se puede conciliar.'}],
src:[['https://cpe.sunat.gob.pe/informacion_general/obligados_cpe','SUNAT: comprobantes de pago electrónicos (contexto de facturas)']],
ver:['El flujo es práctica general de compras y cuentas por pagar. Reglas tributarias y plazos: '+V('área contable y normativa vigente'),'Cifras ficticias.']},

{id:'6.9',title:'Pagos dentro del ciclo del pedido',min:18,
goal:'Ubicar el pago dentro del ciclo del pedido, interpretar sus estados y decidir qué hacer ante rechazos, pendientes y desajustes.',
body:`<p>El pago condiciona todo lo que viene: sin pago aprobado no hay reserva firme, picking ni despacho. El ciclo es: <b>método de pago → autorización → confirmación → reserva y pedido → preparación</b>. Los métodos disponibles (tarjetas, billeteras digitales, etc.) dependen de cada comercio ${V('métodos de pago habilitados en tu empresa')}.</p>
${T(['Estado','Qué significa','Qué haces'],[
['Pendiente','Falta confirmación','Mantén la reserva por el tiempo definido y monitorea'],
['Aprobado','Autorizado y confirmado','El pedido avanza; verifica que se cree en el OMS'],
['Rechazado','No se autorizó','Avisa al cliente, ofrece otro método y libera la reserva si expira'],
['Revertido o reembolsado','Se devolvió el dinero','Coordina con Finanzas y con el estado del pedido']])}
<p>La <b>conciliación</b> compara pagos, pedidos y comprobantes para detectar desajustes (pagos sin pedido, pedidos sin pago). El <b>antifraude</b> es un mundo aparte: aquí solo sabes que algunos pedidos pueden quedar «en revisión» antes de aprobarse. La pregunta operativa es siempre la misma: <b>¿en qué punto del ciclo está el problema?</b></p>`,
example:`<p>En «Retail Andino» (ficticio), un cliente paga y ve «pedido confirmado», pero el OMS no lo muestra. El pago está aprobado en la pasarela; el pedido no se creó. Se escala a TI con el ID de la transacción (capítulo 6.6).</p>`,
ex:{type:'match',intro:'¿Qué haces en cada caso?',opts:['Avisar y ofrecer otro método; liberar la reserva si expira','Mantener la reserva y monitorear hasta el plazo','Escalar a TI con el ID de transacción','Coordinar con Finanzas el reembolso y el estado del pedido'],items:[
{t:'Pago rechazado',a:'Avisar y ofrecer otro método; liberar la reserva si expira'},
{t:'Pago pendiente hace pocos minutos',a:'Mantener la reserva y monitorear hasta el plazo'},
{t:'Pago aprobado, pero el pedido no existe',a:'Escalar a TI con el ID de transacción'},
{t:'Pago revertido después del despacho',a:'Coordinar con Finanzas el reembolso y el estado del pedido'}],
sol:'<p>Bien. Observa que cada caso empieza ubicando el punto del ciclo.</p>',
also:{type:'reveal',task:'Pago confirmado y el pedido no aparece. Escribe tu cadena de verificación.',sol:'<ol><li>¿Existe la transacción aprobada en la pasarela? (ID y hora)</li><li>¿Se creó el pedido en el OMS?</li><li>¿Tiene reserva de stock?</li><li>¿Se asignó a una tienda o almacén?</li><li>¿Llegó a picking?</li></ol><p>El primer «no» marca el punto de escalamiento.</p>'}},
quiz:[
{q:'Un pago pendiente hace pocos minutos…',o:['Se cancela ya','Se monitorea manteniendo la reserva por el tiempo definido','Se ignora','Se factura'],a:1,w:'Puede confirmarse en breve.'},
{q:'La conciliación de pagos compara…',o:['Precios y marcas','Pagos, pedidos y comprobantes','Rutas y horarios','Solo saldos'],a:1,w:'Detecta pagos sin pedido y pedidos sin pago.'},
{q:'Pago aprobado sin pedido creado: el primer punto donde falta el dato es…',o:['La pasarela','El OMS','El cliente','El transporte'],a:1,w:'La pasarela sí tiene el dato; el OMS no.'}],
src:[['https://help.vtex.com/en/docs/tutorials/order-flow-and-status','VTEX: Payment pending y Payment approved']],
ver:['Métodos de pago y reglas de antifraude de tu empresa.','Casos ficticios.']},

{id:'6.10',title:'Mesa de control: 20 incidencias para decidir',min:25,
goal:'Clasificar, priorizar, asignar y decidir la acción de 20 incidencias como en una mesa de control real, y ver dónde fallas.',
body:`<p>Este simulador junta lo de todo el módulo. Para cada incidencia decide <b>tipo, severidad, acción y responsable</b>, y marca las tres que atenderías primero. Al comprobar verás el razonamiento de cada una y en qué decisión fallas más.</p>
<p>Consejos: lee primero el problema y los números (stock, antigüedad, SLA); pregúntate «¿qué daño hace y cuánto tiempo queda?»; y recuerda el orden de acciones (investigar antes de cancelar). Puedes hacerlo en dos tandas de diez: tus respuestas se guardan. Algunas incidencias admiten más de una respuesta razonable; el modelo acepta las variantes principales.</p>`,
example:`<p>En una mesa de control real no decides en frío: tienes un tablero con pedidos, SLA y alertas. Lo que se evalúa en una entrevista es tu método: qué miras primero, qué preguntas, qué escalas y qué cierras.</p>`,
ex:{type:'triage',intro:'Veinte incidencias sintéticas de «Retail Andino». Toma tus decisiones y luego comprueba.',
tipos:['Stock','Picking','Logística','Cliente','Sistema','Pago','Catálogo','Facturación','Seller'],sevs:['Crítica','Alta','Media','Baja'],accs:['Investigar stock','Reasignar','Escalar','Contactar al cliente','Cancelar','Corregir dato','Reprogramar','Monitorear'],resps:AREAS,
top:['INC-07','INC-12','INC-14'],topwhy:'Los tres tienen severidad crítica y afectan a muchos pedidos o generan pérdidas que crecen cada minuto. Siguen de inmediato INC-01 (SLA en 1 h) e INC-17 (plazo de reclamo).',
inc:[
{id:'INC-01',pedido:'PED-10231',estado:'Picking',aging:4,sla:1,prob:'Producto no encontrado en picking (1 televisor, campaña).',tienda:'Surco',sis:2,fis:0,nota:'',k:['Stock','Alta|Crítica','Investigar stock|Reasignar','Inventario|Operaciones / tienda'],why:'Es un caso de stock con SLA en una hora: buscar, contar y reasignar antes de cancelar.'},
{id:'INC-02',pedido:'PED-10244',estado:'Listo para despacho',aging:6,sla:2,prob:'Pedido preparado sin ruta asignada.',tienda:'San Miguel',sis:1,fis:1,nota:'',k:['Logística','Alta','Escalar|Reprogramar','Logística / transporte'],why:'El pedido está listo pero no sale: logística debe asignar ruta antes de que venza.'},
{id:'INC-03',pedido:'PED-10250',estado:'Payment approved',aging:3,sla:5,prob:'Pago confirmado y el pedido no llegó a la tienda.',tienda:'Los Olivos',sis:3,fis:3,nota:'',k:['Sistema|Pago','Alta','Escalar','TI / sistemas|Finanzas'],why:'Falla entre OMS y tienda: escalar con pedido, hora y estado.'},
{id:'INC-04',pedido:'PED-10257',estado:'Entregado',aging:0,sla:0,prob:'Llegó 1 de 2 unidades pedidas.',tienda:'Chorrillos',sis:0,fis:0,nota:'',k:['Stock|Picking','Media','Contactar al cliente|Investigar stock','Servicio al cliente|Operaciones / tienda'],why:'Hay que contactar al cliente y entender por qué se despachó incompleto.'},
{id:'INC-05',pedido:'PED-10261',estado:'En ruta',aging:2,sla:4,prob:'Dirección incompleta, la ruta sale hoy.',tienda:'Surco',sis:1,fis:1,nota:'',k:['Cliente','Media','Contactar al cliente','Servicio al cliente|Logística / transporte'],why:'Confirmar la dirección antes del intento evita un reintento.'},
{id:'INC-06',pedido:'PED-10266',estado:'En ruta',aging:5,sla:3,prob:'Cliente ausente en el segundo intento.',tienda:'San Miguel',sis:1,fis:1,nota:'',k:['Logística|Cliente','Media','Reprogramar','Logística / transporte'],why:'Reprogramar con confirmación previa y registrar el intento.'},
{id:'INC-07',pedido:'SKU TV-55',estado:'Catálogo',aging:0,sla:0,prob:'Error de precio: TV a S/ 100 en lugar de S/ 1000; entran pedidos.',tienda:'Web',sis:8,fis:8,nota:'Ya hay 40 pedidos con ese precio.',k:['Catálogo','Crítica','Escalar|Corregir dato','E-commerce / catálogo|Comercial / compras'],why:'La pérdida crece cada minuto: corregir de inmediato y definir qué hacer con los pedidos.'},
{id:'INC-08',pedido:'PED-10270',estado:'Entregado',aging:0,sla:0,prob:'Boleta emitida con datos de otro cliente.',tienda:'Chorrillos',sis:0,fis:0,nota:'',k:['Facturación','Media','Corregir dato|Escalar','Finanzas'],why:'La corrección documentaria le corresponde a Finanzas (capítulo 5.1).'},
{id:'INC-09',pedido:'PED-10273',estado:'Entregado',aging:0,sla:0,prob:'Producto equivocado: talla M en lugar de L.',tienda:'Los Olivos',sis:0,fis:0,nota:'',k:['Picking','Media','Contactar al cliente|Escalar','Servicio al cliente|Operaciones / tienda'],why:'Cambio prioritario y revisión de causa (escaneo o EAN).'},
{id:'INC-10',pedido:'PED-10278',estado:'Verifying invoice',aging:12,sla:3,prob:'Pedido en «Verifying invoice» hace 12 horas.',tienda:'Surco',sis:1,fis:1,nota:'',k:['Sistema|Facturación','Alta','Escalar','TI / sistemas|Finanzas'],why:'Un estado detenido con SLA vencido requiere escalar la integración de facturación.'},
{id:'INC-11',pedido:'SKU BL-20',estado:'Stock',aging:0,sla:0,prob:'4 unidades reservadas y solo 1 pedido activo del SKU.',tienda:'Chorrillos',sis:6,fis:6,nota:'',k:['Stock|Sistema','Media','Investigar stock|Corregir dato','Inventario|TI / sistemas'],why:'Reserva colgada: liberar reservas huérfanas y revisar el proceso.'},
{id:'INC-12',pedido:'Lote tarde',estado:'Despacho',aging:3,sla:1,prob:'El transportista no recogió el lote de la tarde: 38 pedidos.',tienda:'CD Sur',sis:0,fis:0,nota:'38 pedidos.',k:['Logística','Crítica','Escalar','Logística / transporte'],why:'Afecta a 38 pedidos con SLA en curso: escalar de inmediato para reprogramar el recojo.'},
{id:'INC-13',pedido:'DEV-3021',estado:'Devolución aprobada',aging:120,sla:72,prob:'Devolución aprobada hace 5 días; reembolso pendiente.',tienda:'Surco',sis:0,fis:0,nota:'',k:['Pago|Facturación','Media|Alta','Escalar|Contactar al cliente','Finanzas'],why:'Riesgo de reclamo: acelerar la aprobación y comunicar la fecha.'},
{id:'INC-14',pedido:'SKU CY-11',estado:'Stock',aging:0,sla:0,prob:'SKU de campaña con sistema 15 y físico 0; 11 pedidos afectados.',tienda:'Surco',sis:15,fis:0,nota:'11 pedidos.',k:['Stock','Crítica','Investigar stock|Escalar','Inventario'],why:'Stock fantasma en un SKU de campaña: conteo inmediato, pausar publicación y reasignar.'},
{id:'INC-15',pedido:'PED-10290 / 10291',estado:'Payment approved',aging:1,sla:6,prob:'Pedido duplicado: mismo cliente, mismo pago.',tienda:'Web',sis:2,fis:2,nota:'',k:['Sistema|Cliente','Media','Contactar al cliente|Cancelar','Servicio al cliente'],why:'Confirmar con el cliente, cancelar el duplicado y liberar la reserva.'},
{id:'INC-16',pedido:'6 pedidos',estado:'Ready for handling',aging:10,sla:12,prob:'El seller no confirma el inicio de atención de 6 pedidos.',tienda:'Seller Moda Rímac',sis:0,fis:0,nota:'',k:['Seller','Alta','Escalar','Proveedor o seller|Comercial / compras'],why:'Sin confirmación del seller, el pedido no avanza: escalar con la lista de pedidos.'},
{id:'INC-17',pedido:'REC-0412',estado:'Reclamo',aging:12,sla:15,prob:'Reclamo del Libro de Reclamaciones: día 12 de 15 hábiles.',tienda:'—',sis:0,fis:0,nota:'Quedan 3 días hábiles.',k:['Cliente','Crítica|Alta','Escalar|Contactar al cliente','Servicio al cliente'],why:'El plazo es improrrogable (capítulo 5.2): responder con evidencia a tiempo.'},
{id:'INC-18',pedido:'PED-10302',estado:'Entregado',aging:0,sla:0,prob:'Caja rota y producto dañado en la entrega.',tienda:'Los Olivos',sis:0,fis:0,nota:'',k:['Logística','Media','Contactar al cliente','Servicio al cliente|Logística / transporte'],why:'Aceptar el reclamo con evidencia y coordinar el cambio; revisar el embalaje.'},
{id:'INC-19',pedido:'SKU MX-08',estado:'Stock',aging:0,sla:0,prob:'Stock publicado 0 en la web, pero hay 20 unidades físicas.',tienda:'Chorrillos',sis:20,fis:20,nota:'Ventas perdidas.',k:['Stock|Sistema','Alta','Corregir dato|Investigar stock','Inventario|TI / sistemas'],why:'Bloqueo o sincronización erróneos: se pierden ventas.'},
{id:'INC-20',pedido:'SKU AC-03',estado:'Catálogo',aging:0,sla:0,prob:'Foto de producto incorrecta en la ficha.',tienda:'Web',sis:30,fis:30,nota:'',k:['Catálogo','Baja','Corregir dato|Monitorear','E-commerce / catálogo'],why:'Baja severidad: corregir sin desplazar las prioridades críticas.'}]},
quiz:[
{q:'¿Qué criterio manda para elegir las tres primeras?',o:['El orden numérico','Severidad, cantidad de pedidos o pérdida creciente y tiempo restante','El nombre de la tienda','El azar'],a:1,w:'Daño y tiempo.'},
{q:'Ante «producto no encontrado» con SLA en 1 hora, la acción correcta es…',o:['Cancelar','Investigar stock y reasignar antes de cancelar','Esperar','Cambiar el estado'],a:1,w:'Investigar y reasignar antes de cancelar.'},
{q:'Un error de precio crítico debe…',o:['Esperar al lunes','Corregirse de inmediato','Ignorarse','Solo monitorearse'],a:1,w:'La pérdida crece cada minuto.'}],
src:[],
ver:['Las severidades y las respuestas modelo son un criterio didáctico: en tu empresa las reglas varían.','Todas las incidencias son ficticias.']},

{id:'6.11',title:'Casos «Eres el analista»',min:25,
goal:'Enfrentar tres situaciones completas de operación, del diagnóstico a la acción y al seguimiento, y comparar tu razonamiento con el del modelo.',
body:`<p>Tres casos sin respuesta única. En cada uno decides paso a paso y ves cómo se calificaría tu razonamiento: qué revisas, qué datos pides, a quién contactas, qué KPI está en riesgo, qué hipótesis planteas y qué acción tomas.</p>
<p>Para prepararte a una entrevista, contesta en voz alta antes de elegir: ese es el ejercicio real. Cada caso cierra con un resumen del razonamiento que puedes usar como estructura de respuesta.</p>`,
example:`<p>Fórmula útil para cualquier respuesta: <b>qué veo → qué pregunto → qué hipótesis tengo y cómo la confirmo → qué hago ya → qué análisis dejo para evitar que se repita.</b></p>`,
ex:{type:'scenario',intro:'Elige un caso y decide.',cases:[
{t:'Las 10:00: 85 pedidos pendientes',sit:'<p>Son las 10:00. Hay <b>85 pedidos pendientes</b>. 12 vencen hoy, 7 presentan «producto no encontrado», 4 de ellos son de una misma tienda y 3 son de una campaña.</p>',steps:[
{q:'¿Qué revisas primero?',o:[{t:'Los 12 que vencen hoy, empezando por los que tienen incidencia, y agrupo por tienda y campaña',p:2,f:'Combinas vencimiento e incidencia y buscas patrones.'},{t:'Los 85 uno por uno en orden',p:0,f:'Pierdes tiempo y el riesgo se concentra en pocos.'},{t:'Espero a la tarde para ver cuántos vencen',p:0,f:'Para entonces será tarde.'}]},
{q:'¿Qué datos necesitas?',o:[{t:'Estado, antigüedad, SLA restante, tienda, SKU, stock sistema y físico de esos pedidos',p:2,f:'Son los datos para priorizar y diagnosticar.'},{t:'Solo el nombre del cliente',p:0,f:'No ayuda a decidir.'},{t:'El historial de compras del cliente',p:1,f:'Puede servir para casos críticos, pero no es lo primero.'}]},
{q:'¿A quién contactas?',o:[{t:'Al responsable de la tienda con 4 casos y a Inventario, y aviso al jefe si el impacto crece',p:2,f:'Contactas donde se concentra el problema.'},{t:'A todas las tiendas',p:0,f:'Dispersa el esfuerzo.'},{t:'Al cliente de cada pedido',p:1,f:'Lo harás según el resultado de la búsqueda, no antes.'}]},
{q:'¿Qué KPI está en riesgo?',o:[{t:'On Time y cancelación (y OTIF si hay pedidos incompletos)',p:2,f:'Son los que dependen de estos pedidos.'},{t:'Solo el ticket promedio',p:0,f:'No cambia por esta situación.'},{t:'La conversión',p:0,f:'Es un KPI de la vitrina, no de la operación.'}]},
{q:'¿Qué análisis dejas para evitar recurrencia?',o:[{t:'Concentración por tienda y SKU, revisión de recepciones y ajustes, y conteo cíclico de los SKU críticos',p:2,f:'Atacas la causa raíz.'},{t:'Ninguno: si se resuelve hoy basta',p:0,f:'Sin análisis, vuelve a pasar.'},{t:'Pedir más personal de picking',p:1,f:'Puede ayudar, pero no ataca un problema de stock.'}]}],
cierre:'<p><b>Razonamiento modelo:</b> priorizo por vencimiento e incidencia, agrupo por tienda y campaña, pido datos concretos, contacto donde se concentra el problema, identifico KPI en riesgo y dejo un análisis de causa raíz.</p>'},
{t:'El NPS cayó de 42 a 31',sit:'<p>El NPS transaccional pasó de 42 a 31 en dos semanas. Hay 18 comentarios de detractores; muchos hablan de entregas «fuera de franja».</p>',steps:[
{q:'Antes de sacar conclusiones, ¿qué haces?',o:[{t:'Reviso el tamaño de muestra y el margen de error, y que la encuesta no haya cambiado',p:2,f:'Una caída con pocas respuestas puede ser ruido (capítulo 10.3).'},{t:'Culpo al operador logístico',p:0,f:'Aún no tienes evidencia.'},{t:'Cambio la meta del NPS',p:0,f:'Es maquillar el problema.'}]},
{q:'¿Con qué cruzas el NPS?',o:[{t:'On Time por modalidad y zona, incidencias y comentarios de detractores',p:2,f:'Conectas experiencia con operación.'},{t:'Con el color del producto',p:0,f:'No aporta.'},{t:'Con las ventas de otro mes',p:1,f:'Es demasiado indirecto.'}]},
{q:'Los detractores se concentran en domicilio en una zona con el operador. ¿Qué hipótesis planteas?',o:[{t:'Retrasos del operador en esa zona; lo confirmo con sus indicadores por zona y con las fechas de entrega',p:2,f:'Hipótesis verificable con datos.'},{t:'El cliente exagera',p:0,f:'No descalifiques la señal.'},{t:'Es un problema de precios',p:0,f:'Los comentarios apuntan a otra cosa.'}]},
{q:'¿Qué acción propones?',o:[{t:'Reunión con el operador con casos concretos, plan de mejora de esa zona y ajuste temporal de la promesa',p:2,f:'Combina evidencia, acuerdo y protección de la experiencia.'},{t:'Cambiar de operador de inmediato',p:1,f:'Puede ser necesario, pero antes hay que probar la hipótesis y dar oportunidad de mejora.'},{t:'Esperar dos semanas',p:0,f:'Prolonga el problema.'}]},
{q:'¿Cómo das seguimiento?',o:[{t:'Reporte semanal por zona y una alerta con un umbral basado en límites de control',p:2,f:'Mides si mejora y avisas si vuelve a caer (capítulo 10.5).'},{t:'No hace falta seguimiento',p:0,f:'Sin medición no sabes si funcionó.'},{t:'Mirar el NPS global mensual',p:1,f:'Demasiado agregado para detectar zonas.'}]}],
cierre:'<p><b>Razonamiento modelo:</b> confirmar que la caída es real, cruzar con operación, plantear una hipótesis verificable, actuar con el operador y medir por zona.</p>'},
{t:'Devoluciones por «talla incorrecta»',sit:'<p>En tres días hubo <b>40 devoluciones</b> con el motivo «la talla no corresponde». 33 son del mismo producto.</p>',steps:[
{q:'¿Qué detectas primero?',o:[{t:'La concentración en un solo producto: no es un problema de clientes sino de ese SKU',p:2,f:'Segmentar por producto y motivo es la clave.'},{t:'Que los clientes se equivocan de talla',p:0,f:'Sin evidencia, culpas al cliente.'},{t:'Que hay que subir precios',p:0,f:'No tiene relación.'}]},
{q:'¿Qué hipótesis planteas?',o:[{t:'Error de catálogo: guía de tallas, atributos o EAN de la variante',p:2,f:'Conecta con el capítulo 4.1.'},{t:'Fallas del transportista',p:1,f:'Podría afectar daños, no la talla.'},{t:'Fallas del POS',p:0,f:'No explica la talla.'}]},
{q:'¿Cómo la verificas?',o:[{t:'Comparo la ficha con el producto físico, reviso el EAN escaneado en picking y el detalle de las devoluciones',p:2,f:'Verificas en la fuente.'},{t:'Espero más devoluciones',p:0,f:'Empeora el problema.'},{t:'Cambio la foto sin revisar',p:0,f:'Podrías corregir lo que no era.'}]},
{q:'¿Qué acciones tomas?',o:[{t:'Corregir la ficha o el EAN, avisar a atención al cliente y gestionar los productos devueltos según inspección',p:2,f:'Cortas el origen y ordenas la logística inversa.'},{t:'Solo aceptar las devoluciones',p:1,f:'Resuelves el síntoma, no la causa.'},{t:'Ocultar el producto sin más',p:1,f:'Puede ser un paso temporal, pero hay que corregir.'}]},
{q:'¿Cómo mides que funcionó?',o:[{t:'Tasa de devolución por SKU y por motivo antes y después',p:2,f:'Mide el efecto de la corrección.'},{t:'Ventas totales del mes',p:0,f:'Demasiado genérico.'},{t:'Nada',p:0,f:'No sabrás si mejoró.'}]}],
cierre:'<p><b>Razonamiento modelo:</b> detectar la concentración, plantear una hipótesis de catálogo, verificarla en la fuente, corregir y medir la tasa de devolución del SKU.</p>'}],
also:{type:'opencase',id:'oc_cancel',
sit:'<p>El porcentaje de <b>cancelaciones operativas</b> pasó de <b>3% a 7%</b> durante las últimas dos semanas. Eres el analista de operaciones e-commerce.</p>',
task:'Explica qué investigarías, en qué orden, qué datos necesitarías y qué acciones tomarías inicialmente. Escríbelo como si se lo explicaras a tu jefe.',
pautas:['Separé cancelación voluntaria de cancelación operativa (no son el mismo problema).','Comparé contra el período anterior para confirmar que el aumento es real, no ruido de una semana chica.','Segmenté por tienda, categoría y período para ver si está concentrado o es general.','Revisé stock mostrado (sistema) contra stock físico en la tienda o zona donde se concentra.','Revisé incidencias de picking (producto no encontrado, sobreventa) de esos pedidos.','Identifiqué si hay concentración (una tienda, una categoría, una fecha de inicio) o si es transversal.','Consulté al responsable correspondiente (tienda, inventario o TI según lo que encontré) antes de escalar más arriba.','Propuse una acción inicial concreta, no solo "investigar más".','Definí cómo mediría si la acción funcionó (qué KPI y en cuánto tiempo reviso de nuevo).'],
modelo:'Antes de nada, separo cancelación voluntaria de operativa y comparo contra la semana anterior. Si el aumento es real, segmento por tienda y categoría: si se concentra en un punto, reviso ahí el stock sistema vs. físico y las incidencias de picking recientes. Si encuentro una discrepancia, aviso al responsable de esa tienda y a inventario, propongo un conteo o ajuste, y me comprometo a revisar la cancelación de esa tienda en 3-5 días para confirmar que bajó.'}},
quiz:[
{q:'Una buena respuesta de entrevista sigue…',o:['Solo una definición','Qué veo → qué pregunto → hipótesis → acción → análisis posterior','Solo la solución','Solo el KPI'],a:1,w:'Muestra método.'},
{q:'Los 33 casos de 40 devoluciones en un SKU indican…',o:['Un problema general de clientes','Un problema localizado, posiblemente de catálogo','Suerte','Un error del cliente'],a:1,w:'La concentración apunta al SKU.'},
{q:'Antes de reaccionar a una caída del NPS, verificas…',o:['Nada','Muestra y margen de error','El color','El precio'],a:1,w:'Evita reaccionar al ruido.'}],
src:[],
ver:['Casos y cifras ficticios; sirven para entrenar el razonamiento, no como datos de una empresa.']}
,
{id:'6.12',title:'Diagnóstico de caídas de KPI: On Time, Cancelación, Fill Rate y OTIF',min:22,
goal:'Aplicar el mismo método de diagnóstico (causa probable, impacto, qué investigar, responsable, acción) a caídas de los 4 KPI de reporte más citados, no solo a incidencias puntuales.',
body:`<p>Hasta ahora practicaste el diagnóstico sobre <b>incidencias individuales</b> (un pedido, una tienda). Aquí se aplica el mismo razonamiento a una <b>caída de KPI en el reporte</b>: el jefe te muestra que un número bajó y te pregunta «¿qué harías?». El método es el mismo que ya conoces: <b>¿está concentrado o es general? → ¿qué cambió? → ¿qué dato lo confirma? → ¿a quién involucro? → ¿qué acción propongo?</b></p>
<p>Toca cada situación para ver cómo se razona, y después practica tú eligiendo a quién recurrirías.</p>`,
example:`<p>Los 4 KPI están conectados: una caída de <b>Fill Rate</b> casi siempre golpea también el <b>OTIF</b> (porque OTIF exige a tiempo Y completo). Por eso conviene mirar más de un KPI a la vez, no uno aislado.</p>`,
ex:{type:'cat',intro:'Elige una situación para ver cómo se diagnostica.',items:[
{t:'On Time cayó de 94% a 87% esta semana',cat:'On Time',kpi:'On Time',causa:'Puede ser general (capacidad vendida de más o un transportista con retraso en todas partes) o concentrada (una tienda, una franja, un transportista puntual).',impacto:'Pedidos fuera de la promesa mostrada al cliente; sube el riesgo de reclamos y puede arrastrar el NPS.',invest:['Segmentar On Time por tienda, franja, modalidad y día','Revisar si se vendió por encima de la capacidad de alguna franja','Revisar si un transportista o ruta concentra los retrasos','Revisar si aumentaron los pedidos que entran después del corte'],resp:'Operaciones (tienda o franja)',apoyo:'Planificación de franjas y capacidad, o Logística / TMS si es transporte',accion:'Si es una franja sobrevendida: cerrarla temporalmente o reforzar personal. Si es un transportista: contactarlo con evidencia y, mientras se resuelve, ajustar temporalmente la promesa mostrada.'},
{t:'Cancelación por «producto no encontrado» concentrada en una tienda y categoría desde una fecha puntual',cat:'Cancelación',kpi:'Cancelación',causa:'Cuando se concentra en una tienda, una categoría y una fecha de inicio, casi siempre es una discrepancia entre el stock del sistema y el físico (recepción mal ingresada, merma sin registrar, o reservas que no calzan).',impacto:'Pedidos que nunca se pueden entregar: mala experiencia y venta ya reservada que se pierde.',invest:['Confirmar la concentración: tienda, categoría y fecha de inicio','Comparar stock sistema vs. físico de los SKU afectados','Revisar la última recepción de esa categoría en esa tienda','Revisar reservas duplicadas o ajustes pendientes'],resp:'Inventario / Almacén (WMS)',apoyo:'Operaciones (tienda o franja) de la tienda afectada',accion:'Pedir un conteo cíclico o ajuste de los SKU más afectados, y bloquear temporalmente la venta online de esos SKU si la discrepancia es grande.'},
{t:'El Fill Rate baja pero el On Time se mantiene estable',cat:'Fill Rate',kpi:'Fill Rate',causa:'Si On Time no baja pero el Fill Rate sí, el problema no es de tiempo sino de completar el pedido: sobreventa o quiebre de stock en SKU puntuales.',impacto:'El cliente recibe menos de lo pedido; afecta directamente al OTIF aunque el pedido llegue a tiempo.',invest:['Identificar los SKU con más unidades no entregadas','Revisar si esos SKU tuvieron sobreventa (más reservado que físico)','Revisar si el picking reporta faltantes recurrentes de esos SKU','Revisar si son pedidos de una campaña o promoción reciente'],resp:'Inventario / Almacén (WMS)',apoyo:'Marketplace / Sellers si el SKU es 3P',accion:'Ajustar el stock disponible publicado de esos SKU hasta confirmar el físico, y avisar a comercial si viene de una promoción con demanda mal calculada.'},
{t:'La brecha entre On Time y OTIF crece: llegan a tiempo pero incompletos',cat:'OTIF',kpi:'OTIF',causa:'OTIF exige a tiempo Y completo. Si cae más que On Time solo, la brecha viene del «In Full»: apunta a picking/packing, no a transporte.',impacto:'Es el KPI que mejor resume la experiencia real de recibir todo lo pedido cuando se prometió.',invest:['Calcular la brecha entre On Time y OTIF por tienda','Revisar la tasa de error de picking de esa tienda o turno','Revisar si coincide con un turno o con personal nuevo','Cruzar con las mismas causas del Fill Rate'],resp:'Operaciones (tienda o franja)',apoyo:'Inventario / Almacén (WMS)',accion:'Reforzar el checklist de packing (verificar unidades antes de cerrar el pedido) en la tienda o turno señalado, y dar seguimiento a la tasa de error la semana siguiente.'}
],
also:{type:'route',areas:['Operaciones (tienda o franja)','Logística / TMS','Inventario / Almacén (WMS)','TI / Integración de sistemas','Atención al cliente / CRM','Marketplace / Sellers','Planificación de franjas y capacidad','Jefe de operaciones (escalamiento)'],items:[
{t:'On Time cayó de 94% a 87% esta semana, sin saber aún si es general o concentrado.',r:['Operaciones (tienda o franja)'],a:['Planificación de franjas y capacidad','Logística / TMS'],info:'Segmentación por tienda/franja/modalidad, y evidencia de capacidad sobrevendida o de un transportista con retraso.',why:'Antes de escalar más arriba, quien opera la tienda o franja confirma dónde se concentra.'},
{t:'Las cancelaciones por «producto no encontrado» se concentran en una tienda y categoría desde una fecha puntual.',r:['Inventario / Almacén (WMS)'],a:['Operaciones (tienda o franja)'],info:'SKU afectados, comparación stock sistema vs. físico y fecha de la última recepción.',why:'Es una discrepancia de inventario: el almacén confirma el físico antes de que operaciones actúe con el cliente.'},
{t:'El Fill Rate baja pero el On Time se mantiene estable.',r:['Inventario / Almacén (WMS)'],a:['Marketplace / Sellers'],info:'Los SKU con más unidades faltantes, y si tuvieron sobreventa o son de un seller 3P.',why:'Es un problema de disponibilidad de SKU, no de tiempo de entrega.'},
{t:'La brecha entre On Time y OTIF crece: llegan a tiempo pero incompletos.',r:['Operaciones (tienda o franja)'],a:['Inventario / Almacén (WMS)'],info:'Tasa de error de picking por tienda/turno y si coincide con personal nuevo.',why:'El problema está en el armado del pedido (picking/packing), que reporta a operaciones de la tienda.'}
]}},
quiz:[
{q:'On Time baja de forma pareja en todas las tiendas y franjas. ¿Qué sospechas primero?',o:['Un problema de catálogo','Algo general: capacidad vendida de más o un transportista amplio','Un solo picker','El precio del producto'],a:1,w:'Una caída pareja apunta a una causa general, no a un punto aislado.'},
{q:'El Fill Rate cae pero el On Time se mantiene. ¿Dónde miras primero?',o:['En el transportista','En sobreventa o quiebre de stock de SKU puntuales','En el precio','En el NPS'],a:1,w:'Si el tiempo está bien pero falta completar el pedido, el problema es de disponibilidad, no de transporte.'},
{q:'La brecha entre On Time y OTIF crece. ¿Qué área tiendes a involucrar primero?',o:['Marketing','Operaciones de la tienda o turno (picking/packing)','Finanzas','El cliente'],a:1,w:'OTIF cayendo más que On Time apunta al «In Full»: picking y packing.'}],
src:[],
ver:['Situaciones ficticias construidas para practicar el método de diagnóstico; los nombres de áreas pueden variar entre empresas.']}
]});
